version: '3.7'
services:
  special-mongodb:
    image: mongo:4.4.17-rc2
    container_name: special-mongodb
    restart: always
    ports:
      - "37017:27017"
    volumes:
      - ./special/mongo/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: special
      MONGO_INITDB_ROOT_PASSWORD: special
  mongo-express:
    image: mongo-express
    container_name: special-mongo-express
    restart: always
    ports:
      - "38081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: special
      ME_CONFIG_MONGODB_ADMINPASSWORD: special
      ME_CONFIG_MONGODB_URL: mongodb://special:special@host.docker.internal:37017/
