version: '3.7'
services:
  special-mongodb:
    container_name: special-mongodb
    image: mongo:4.4.17-rc2
    ports:
      - "37017:27017"
  special-adminer:
    image: adminer
    ports:
      - "38080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=special-mongodb
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce
