spring:
  data:
    mongodb:
      host: localhost
      port: 37017
      authentication-database: admin
      username: special
      password: special
      database: special

special:
  oauth2:
    client:
      registration:
        kakao:
          client-id:
          redirect-uri: http://localhost:8080/api/v1/login/oauth2/code
        google:
          client-id:
          client-secret:
          redirect-uri: http://localhost:8080/api/v1/login/oauth2/code
