spring:
  data:
    mongodb:
      host: localhost
      port: 37017
      authentication-database: admin
      username: special
      password: special
      database: special
  config:
    import:
      - backend-config/auth.yml
      - backend-config/s3_info.yml

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
---

spring:
  config:
    activate:
      on-profile: dev
server:
  ssl:
    enabled: true
    key-store: /root/keystore.p12
    key-store-type: PKCS12
    key-store-password: tmvptufXla!@

---