spring:
  data:
    mongodb:
      host: localhost
      port: 37017
      authentication-database: admin
      username: special
      password: special
      database: special
  config:
    import:
      - backend-config/auth.yml
      - backend-config/s3_info.yml
